source 'https://rubygems.org'
ruby '>= 2.6.0', '<= 2.7'
gem 'yaml'
gem 'mysql2'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'haml'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'activerecord-mysql2-adapter'
gem 'rake'
