development:
  adapter: mysql2
  database: baby_tracking
  username: root
  password: vecfdsminjkl
  host: localhost
test:
  adapter: mysql2
  database: library_test
  username: root
  password: 
  host: localhost
production:
  adapter: mysql2
  database: library_production
  username: root
  password: 
  host: localhost